import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/css/globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import NextTopLoader from 'nextjs-toploader';
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider"
import { Analytics } from "@vercel/analytics/react"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Welcome to KuickShare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
      <Toaster/>
      <Analytics/>
      <NextTopLoader
      color="#000000"
      initialPosition={0.08}
      crawlSpeed={200}
      height={3}
      crawl={true}
      showSpinner={true}
      easing="ease"
      speed={200}
      shadow="0 0 10px #2299DD,0 0 5px #2299DD"
      template='<div class="bar" role="bar"><div class="peg"></div></div> 
      '
      zIndex={1600}
      showAtBottom={false}
      />
        <Navbar/>
        {children}

        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
