import type { Metadata } from "next";

import "@/css/globals.css";



export const metadata: Metadata = {
    title: "Create your Account - KuickShare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      
        {children}
      
    </>
  );
}
